### ISSUE TITLE
Exit: Illegal number: -1

### ISSUE THREAD

**Issue by polzy** [pihomeserver/Pi-Hotspot#4]
Hi, 
I have a problem with sur bash script  : 

** Activating the WAN interface
** Activating the LAN interface
** Installing debconf tools
**
** Something went wrong with the last command. Please check the log file
**
pihotspot.sh: 46: exit: Illegal number: -1

Can you halp me ? 
Thanks you

**Comment by pihomeserver** [comment]
OK the exit code is not correct but something went wrong with the installation of debconf Can you please look at the last lines of the log file in /var/log/pihotspot.log ?
-------- Message d'origine --------De : polzy <notifications@github.com> Date : 28/09/2016  09:23  (GMT+01:00) À : pihomeserver/Pi-Hotspot <Pi-Hotspot@noreply.github.com> Objet : [pihomeserver/Pi-Hotspot] Exit: Illegal number: -1 (#4) 
Hi, 

I have a problem with sur bash script  : 

** Activating the WAN interface

** Activating the LAN interface

** Installing debconf tools

**

** Something went wrong with the last command. Please check the log file

**

pihotspot.sh: 46: exit: Illegal number: -1

Can you halp me ? 

Thanks you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pihomeserver/Pi-Hotspot","title":"pihomeserver/Pi-Hotspot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pihomeserver/Pi-Hotspot"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Exit: Illegal number: -1 (#4)"}],"action":{"name":"View Issue","url":"https://github.com/pihomeserver/Pi-Hotspot/issues/4"}}}

**Comment by pihomeserver** [comment]
OK the exit code is not correct but something went wrong with the installation of debconf Can you please look at the last lines of the log file in /var/log/pihotspot.log ?

**Comment by polzy** [comment]
Hi, 
Yes, thanks you

** 
** Log file created : /var/log/pihotspot.log
** Use command 'tail -f /var/log/pihotspot.log' in a new console to get installation details
** Checking if wlan0 interface already exists
wlan0     Link encap:Ethernet  HWaddr 00:08:d3:4a:12:b1  
** Update interface configuration
** Activating the WAN interface
ifup: interface eth0 already configured
** Activating the LAN interface
RTNETLINK answers: File exists
Failed to bring up wlan0.
** Installing debconf tools
Reading package lists...
Building dependency tree...Segmentation fault
** 
** Something went wrong with the last command. Please check the log file
**

**Comment by pihomeserver** [comment]
The problem comes from the installation of the tools debconf. apt-get crashed 
Try manually to install them, solve the issue (not related to the script) and try to run the script again
You can use the command 
`
apt-get install debconf-utils
`

**Comment by pihomeserver** [comment]
The return code has been corrected. Thanks for the issue report
